services:
  mysql:
    container_name: mysql-db-bsn
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: book_social_network
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql:
    driver: local
