services:
  mysql:
    container_name: mysql-db-bsn
    image: mysql  # Use the MySQL 5.7 image, or another version you prefer
    environment:
      MYSQL_ROOT_PASSWORD: 1234  # Change as needed
      MYSQL_DATABASE: book_social_network
    #  MYSQL_USER: root
      MYSQL_PASSWORD: 1234
    volumes:
      - mysql:/var/lib/mysql  # MySQL data directory
    ports:
      - "3307:3306"  # MySQL default port
    networks:
      - spring-demo
    restart: unless-stopped

  mail-dev:
    container_name: mail-dev-bsn
    image: maildev/maildev
    ports:
      - "1080:1080"  # MailDev Web interface
      - "1025:1025"  # MailDev SMTP server
    networks:
      - spring-demo

networks:
  spring-demo:
    driver: bridge

volumes:
  mysql:
    driver: local
